version: '3'
services:
  cassandra2:
    image: 'docker.io/bitnami/cassandra:3-debian-10'
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './cassandra/cassandra.cql:/docker-entrypoint-initdb.d/script.cql'
    environment:
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_USER=cassandra

  swapi-api:
    image: 'robkler/swapi-api:latest'
    container_name: swapi-api
    ports:
      - "8080:8080"
    depends_on:
      - cassandra2
    environment:
      API_PORT: "8080"
      CASSANDRA_HOST: "cassandra2"
      CASSANDRA_USERNAME: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"


