name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Docker login
        run: docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD robkler
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag swapi-api:lastest
      - name: Docker push
        run:  docker push robkler/swapi-api:latest